name: Build

on:
  push:
  workflow_dispatch:

jobs:
  Build-PC:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
    - name: Obtain latest version of the repository
      uses: actions/checkout@v3
    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install requirements with PIP
      run: pip install -r requirements.txt
    - name: Install pyinstaller
      run: pip install pyinstaller
    - name: Build RiiTag RPC
      run: pyinstaller riitag-rpc.spec
    - name: Publish Build Artifacts
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.os }}
        path: dist
  
  Build-RPI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [rpi_4b_aarch64]
        include:
        - target: rpi_4b_aarch64
          cpu: cortex-a53
          cpu_info: cpuinfo/raspberrypi_4b
          base_image: raspios_lite_arm64:latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Raspberry pi release
      uses: pguyot/arm-runner-action@v2
      with:
        base_image: ${{ matrix.base_image }}
        cpu: ${{ matrix.cpu }}
        cpu_info: ${{ matrix.cpu_info }}
        bind_mount_repository: true
        commands: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install -r requirements.txt
          pip3 install pyinstaller
          pyinstaller riitag-rpc.spec
    - name: Publish Build Artifacts
      uses: actions/upload-artifact@master
      with:
        name: rpi-4b-latest
        path: dist
